---
- name: Fix DNS
  include_tasks: subtasks/fix_dns.yml
  tags:
    - fix_nm
    - fix_search_path

- name: Install GoCD
  include_tasks: subtasks/install_gocd.yml
  tags: 
    - add_go_repo
    - install_go
