restricted_accounts:
  - { user_name: ruser7, user_group: ruser7, user_groups: rusers, user_home: /home/ruser7, user_comment: "Restricted user", user_passwd: "pass123", user_passwd_expiry: "28", user_keygen: yes }

restricted_commands:
  - { command: "/usr/bin/ssh", mode: "0755" }
 # - { command: "/usr/bin/ls", mode: "0755" }

action: adduser 

typescript_logs: /var/log/ssh
typescript_owner: root
typescript_group: rusers
