---
- name: Adding xxxman user
  import_tasks: os/xxxman.yml
  when: target_user == "xxxman"

- name: Adding other os users
  import_tasks: os/users.yml
  when: ( target_user == "osusers" )
  #when: host_state is defined and host_force is defined
  #
- name: Adding unix adm users as default
  #include_vars:
  #  file: users_unix_admins
  import_tasks: os/users.yml
  when: ( target_user == "unix" or target_user is undefined )

