---
- name: Add user
  user:
    name: "{{ user_name }}"
    comment: "{{ user_comment }}"
    #expires: -1 
    state: present

- name: Create .ssh directory
  file:
    path: "{{ user_home }}{{ user_name }}/.ssh"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0700
    recurse: no

- name: Allow "{{ user_name }}" sudo passwordless
  lineinfile:
    path: /etc/sudoers
    line: "{{ user_name }} ALL=NOPASSWD: ALL"
    validate: '/usr/sbin/visudo -cf %s'

- name: Reenforce user account expiry.
  command: /usr/bin/passwd -x -1 "{{ user_name }}"
