---
###################### Test #######################
- name: Test that it is used on Linux only. Part A
  assert:
    that: 
      - "ansible_os_family == 'RedHat'"
  tags:
    - set_logindefs
    - test_pre_logindefs_1

################# Make the change ###################

#- name: Copy rsyslog file.
#  copy:
#    src: "{{FILE_SYSLOG_SRCPATH}}"
#    dest: "{{FILE_SYSLOG_DESTPATH}}"
#    owner: root
#    group: root
#    mode: 0644
#    backup: no
#  tags:
#    - set_logindefs

- name: Update login.defs file.
  template:
    src: "{{TEMPLATE_LOGINDEFS_SRC}}"
    dest: "{{TEMPLATE_LOGINDEFS_DEST}}"
    owner: root
    group: root
    mode: 0644
  tags:
    - set_logindefs
