---
- name: Set NetworkManaged to no
  lineinfile:
    path: "/etc/sysconfig/network-scripts/ifcfg-eth0"
    line: NM_CONTROLLED="NO"
    regexp: "^NM_CONTROLLED"
    state: present
  tags:
    - fix_nm_

- name: Set search path
  lineinfile:
    path: "/etc/resolv.conf"
    line: search mega.lan
    regexp: "^#"
    state: present
  notify: restart network
  tags:
    - fix_search_path
