---
#- name: Get GoCD
#  get_url: 
#     url: "{{ item.url }}{{ item.name }}"
#     dest: "/tmp/{{ item.name }}"
#     #validate_certs: False 
#     #force_basic_auth: yes
#  with_items:
#    - "{{ gocd_server_url }}"
#  tags:
#    - download_gocd

- name: Add GoCD repo
  yum_repository:
    name: GoCD
    description: GoCD Yum repo
    file: gocd
    baseurl: https://download.gocd.org/
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.gocd.org/GOCD-GPG-KEY.asc
  tags:
    - add_go_repo

- name: Install go-servers dependencies
  yum:
    name: "{{ item.package }}"
    state: "{{ item.state }}"
  with_items: "{{ gocd_packages }}"
  tags:
    - install_go

#- name: Add rules to iptables
#  iptables:
#    chain: INPUT
#    protocol: tcp
#    destination_port: 8153
#    ctstate: NEW
#    syn: match
#    jump: ACCEPT
#    comment: Accept new GoCD connections.
#  tags:
#    - fw_rules
#  notify:
#    - restart iptables
#
- name: Stop iptables
  service:
    name: iptables
    enabled: False
    state: stopped
  tags:
    - fw_rules

- name: Start go server
  service:
    name: go-server
    state: started
