---
- name: Apply template
  template:
    src: "{{role_path}}/templates/{{item.1.tmpl}}"
    dest: "/home/kaloong/tmp/{{item.1.tmpl | regex_replace('.j2') }}"
  with_subelements:
    - "{{ backups }}"
    - backup
