---
###################### Test #######################
- name: Test that it is used on Linux only. Part A
  assert:
    that: 
      - "ansible_os_family == 'RedHat'"
  tags:
    - set_selinux
    - test_pre_selinux

################# Make the change ###################

#- name: Copy rsyslog file.
#  copy:
#    src: "{{FILE_SYSLOG_SRCPATH}}"
#    dest: "{{FILE_SYSLOG_DESTPATH}}"
#    owner: root
#    group: root
#    mode: 0644
#    backup: no
#  tags:
#    - set_selinux

# Put SELinux in permissive mode, logging actions that would be blocked.
- name: Set selinux policy.
  selinux:
    policy: '{{VAR_SELINUXTYPE}}'
    state:  '{{VAR_SELINUX}}'
  tags:
    - set_selinux
