---
###################### Test #######################
- name: Test that it is used on Linux only. Part A
  assert:
    that:
      - "ansible_os_family == 'RedHat'"
  tags:
    - set_pwquality
    - test_pre_pwquality_1

################# Make the change ###################

#- name: Copy rsyslog file.
#  copy:
#    src: "{{FILE_SYSLOG_SRCPATH}}"
#    dest: "{{FILE_SYSLOG_DESTPATH}}"
#    owner: root
#    group: root
#    mode: 0644
#    backup: no
#  tags:
#    - set_pwquality

- name: Copy pwquality file.
  template:
    src: "{{TEMPLATE_PWQUALITY_SRC}}"
    dest: "{{TEMPLATE_PWQUALITY_DEST}}"
    owner: root
    group: root
    mode: 0644
  tags:
    - set_pwquality
