---
iso_url:
   "6.8": "http://vault.centos.org/centos/6.8/os/{{ isolinux_arch_version }}/" 
   "6.9": "http://vault.centos.org/centos/6.9/os/{{ isolinux_arch_version }}/"
   "6.10": "http://mirror.centos.org/centos/6.10/os/{{ isolinux_arch_version }}/"
   "6": "http://mirror.centos.org/centos/6/os/{{ isolinux_arch_version }}/"
   "7.0.1406": "http://vault.centos.org/centos/7.0.1406/os/x86_64/"
   "7.1.1503": "http://vault.centos.org/centos/7.1.1503/os/x86_64/"
   "7.2.1511": "http://vault.centos.org/centos/7.2.1511/os/x86_64/"
   "7.3.1611": "http://vault.centos.org/centos/7.3.1611/os/x86_64/"
   "7.4.1708": "http://vault.centos.org/centos/7.4.1708/os/x86_64/"
   "7.5.1804": "http://vault.centos.org/centos/7.5.1804/os/x86_64/"
   "7.6.1810": "http://mirror.centos.org/centos/7.6.1810/os/x86_64/"
   "7"       : "http://mirror.centos.org/centos/7/os/x86_64/"

# isolinux_image_url:     "http://vault.centos.org/centos/{{ isolinux_os_version }}/os/{{ isolinux_arch_version }}/isolinux/"
# isolinux_7_image_url:   "http://mirror.centos.org/centos/{{ isolinux_os_version }}/os/{{ isolinux_arch_version }}/isolinux/"
c6_iso_dvd_1_url: "http://mirror.nsc.liu.se/centos-store/centos/{{ iso_linux_version }}/isos/{{ isolinux_arch_version }}/Centos-{{ isolinux_os_version }}-{ isolinux_arch_version }}-bin-DVD1.iso"
c6_iso_dvd_2_url: "http://mirror.nsc.liu.se/centos-store/centos/{{ iso_linux_version }}/isos/{{ isolinux_arch_version }}/Centos-{{ isolinux_os_version }}-{ isolinux_arch_version }}-bin-DVD2.iso"
c701406_iso_everything_url: "http://mirror.nsc.liu.se/centos-store/centos/7.0.1406/isos/x86_64/Centos-7.0-1406-Everything.iso"
c711503_iso_everything_url: "http://mirror.nsc.liu.se/centos-store/centos/7.1.1503/isos/x86_64/Centos-7-x86_64-Everything-1503-01.iso"
c721511_iso_everything_url: "http://mirror.nsc.liu.se/centos-store/centos/7.2.1511/isos/x86_64/Centos-7-x86_64-Everything-1511.iso"
c731611_iso_everything_url: "http://mirror.nsc.liu.se/centos-store/centos/7.3.1611/isos/x86_64/Centos-7-x86_64-Everything-1611.iso"
c741708_iso_everything_url: "http://mirror.nsc.liu.se/centos-store/centos/7.4.1708/isos/x86_64/Centos-7-x86_64-Everything-1708.iso"
c751804_iso_everything_url: "http://mirror.nsc.liu.se/centos-store/centos/7.5.1804/isos/x86_64/Centos-7-x86_64-Everything-1804.iso"
c761810_iso_everything_url: "http://mirrors.coreix.net/centos/7.6.1810/isos/x86_64/CentOS-7-x86_64-Everything-1810.iso"

os_version:	        "6.10"
isolinux_arch_version:	x86_64
isolinux_cfg:		
  "6": isolinux_6.cfg.j2
  "7": isolinux_7.cfg.j2
isolinux_ks:		
  "6": kickstart_6.ks.j2
  "7": kickstart_7.ks.j2
bootiso_local_dir:      /tmp/bootiso
# bootiso_filename:      "{{ '%Y%m%d' | strftime( ansible_date_time.epoch ) }}_{{ inventory_hostname }}.iso"
bootiso_filename:       "{{ inventory_hostname }}.iso"

isolinux_boot_files:
  "6": 
    - "boot.msg"
    - "grub.conf"
    - "initrd.img"
    - "isolinux.bin"
    - "isolinux.cfg"
    - "memtest"
    - "splash.jpg"
    - "vesamenu.c32"
    - "vmlinuz"
  "7": 
    - "boot.msg"
    - "grub.conf"
    - "initrd.img"
    - "isolinux.bin"
    - "isolinux.cfg"
    - "memtest"
    - "splash.png"
    - "vesamenu.c32"
    - "vmlinuz"

#isolinux_boot_files_6:
#  - "boot.msg"
#  - "grub.conf"
#  - "initrd.img"
#  - "isolinux.bin"
#  - "isolinux.cfg"
#  - "memtest"
#  - "splash.jpg"
#  - "vesamenu.c32"
#  - "vmlinuz"
#
#isolinux_boot_files_7:
#  - "boot.msg"
#  - "grub.conf"
#  - "initrd.img"
#  - "isolinux.bin"
#  - "isolinux.cfg"
#  - "memtest"
#  - "splash.png"
#  - "vesamenu.c32"
#  - "vmlinuz"
