---
- name: Destroy VM on VMWare
  vmware_guest:
    hostname: '{{ deployment_vcenter }}'
    username: '{{ deployment_user }}'
    password: '{{ deployment_pass }}'
    datacenter: '{{ deployment_datacenter }}'
    validate_certs: no
    folder: '{{ deployment_folder }}'
    name: '{{ inventory_hostname }}'
    #state: poweredon
    state: '{{ guest_vm_state }}'
    force: '{{ guest_vm_force }}'
    guest_id: '{{ guest_id }}'
    esxi_hostname: '{{ esxi_host }}'
  delegate_to: localhost
  tags:
    - destroy_vm
  #  register: newly_deployed_vm

  #- debug:
  #  msg: "{{ newly_deployed_vm.instance.ipv4 }}........"
  #  when: newly_deployed_vm.instance is defined
