---
###################### Test #######################
- name: Test that it is used on Linux only. Part A
  assert:
    that: 
      - "ansible_os_family == 'RedHat'"
  tags:
    - set_ulimit
    - test_pre_ulimit_1

- name: Test that {{ETC_PROFILE}} file exists. Part B
  stat: 
    path: "{{ETC_PROFILE}}"
  register: p
  tags:
    - set_ulimit
    - test_pre_ulimit_1

- name: Test that {{ETC_PROFILE}} file exists. Part C
  assert:
    that:
      - p.stat.exists and p.stat.path
  tags:
    - set_ulimit
    - test_pre_ulimit_1


################# Make the change ###################
- name: Set ulimit as per build standard in {{ETC_PROFILE}}
  lineinfile:
    path: "{{ETC_PROFILE}}"
    #line: "ulimit -S -c 0 >/dev/null 2>&1"
    line: "{{ULIMIT_VAR_1}}" 
    regexp: ulimit
    insertafter: (?i) pathmunge
    state: present
  tags:
    - set_ulimit


###################### Test #######################
- name: Test that ulimit is set in {{ETC_PROFILE}}. Part A
  shell: "/bin/cat {{ETC_PROFILE}}"
  register: cmd_result 
  tags: 
    - set_ulimit
    - test_post_ulimit_1

- name: Test that ulimit is set in {{ETC_PROFILE}}. Part B
  assert:
    that:
      - "{{ULIMIT_VAR_1}} in cmd_result.stdout"
      - "'error' not in cmd_result.stderr"
  tags: 
    - set_ulimit
    - test_post_ulimit_1
