---
- hosts: dev_vms
  vars_files: 
    - ../inventories/dev/group_vars/deployment_vars
    - ../inventories/dev/host_vars/centos7_vars
  #become: true
  gather_facts: false
  connection: local
  roles: 
    - ../roles/build_iso 	# VMWware roles
