---
- hosts: build_vms
  vars_files: 
    - ../inventories/build/group_vars/deployment_vars
    - ../inventories/build/host_vars/centos_vars
  #become: true
  gather_facts: false
  connection: local
  roles: 
    - ../roles/build_iso 		# VMWware roles
    - ../roles/build_vm 		# VMWware roles
