---
- hosts: dev_vms
  vars_files: 
    - ../inventories/dev/group_vars/deployment_vars
    - ../inventories/dev/host_vars/centos_vars
  #become: true
  gather_facts: false
  connection: local
  roles: 
    - ../roles/build_vm 		# VMWware roles
