---
- hosts: build_vms
  vars_files: 
    - ../inventories/build/group_vars/mihome_vcenter_vars
    - ../inventories/build/group_vars/centos610_vars
  #become: true
  gather_facts: false
  connection: local
  roles: 
    - ../roles/build_iso 	# VMWware roles
