---
- hosts: newbuild15_vm
  vars_files:
  #  - ../inventories/build/group_vars/mihome_vcenter_vars
    - ../inventories/build/group_vars/newusers_vars
  vars:
    - gitrepo_name: newrepo.git
    - gitrepo_path: /srv/git
  become: true
  gather_facts: true
  #connection: local
  roles:
    - { role: "../roles/add_users" }                                            # Generate bootisos
    - { role: "../roles/build_gitrepo" }                                            # Generate bootisos
