---
- hosts: newbuild8_vm
  vars_files: 
    - ../inventories/build/group_vars/mihome_vcenter_vars
    - ../inventories/build/group_vars/centos7_vcenter_vars
  #become: true
  gather_facts: true
  connection: local
  roles: 
    - ../roles/build_bootiso 	                                # Generate bootisos
      #- { role: "../roles/transfer_bootiso", tags: "via_nfs" }       # Transfer bootisos to DataStore
      #- { role: "../roles/vmware_adm", tags: "deploy_vm", vars: { guest_vm_state : "poweredon" } }		# Deploy VMs with bootisos
