---
- name: Check if rbash exists.
  stat:
    path: /bin/rbash
  register: sym
  tags:
    - os_restricted_shell

- name: Make rbash
  copy:
    src: /bin/bash
    dest: /bin/rbash
    owner: root
    group: root
    mode: 0755
  when: ( sym.stat.exists == False )
  tags:
    - os_restricted_shell

- name: Setup Restricted shell for user.
  user:
    name: "{{ item.user_name }}"
    shell: /bin/rbash
    comment: "{{ item.user_comment }}"
    password: "{{ item.user_passwd | password_hash('sha512','mysalt') }}"
    state: "{{ item.user_state }}"
  with_items:
    - "{{ restricted_accounts }}"
  when: ( "{{ item.user_name }}" is defined and "{{ item.user_state }}" == "present" )
  tags:
    - os_restricted_shell

- name: Reenforce user account expiry.
  command: /usr/bin/chage -M "{{ item.user_expiry }}" "{{ item.user_name }}"
  with_items:
    - "{{ restricted_accounts }}"
  when: ( "{{ item.user_name }}" is defined and "{{ item.user_state }}" == "present" )
  tags:
    - os_restricted_shell

- name: Create home bin directory
  file:
    path: "/home/{{ item.user_name }}/bin"
    owner: "{{ item.user_name }}"
    group: "{{ item.user_groups }}"
    state: directory
  with_items:
    - "{{ restricted_accounts }}"
  when: ( "{{ item.user_name }}" is defined and "{{ item.user_state }}" == "present" )
  tags:
    - os_restricted_shell

- name: Copy commands to restricted shell bin folder
  copy:
    src: "{{ item[1].command }}"
    dest: "/home/{{ item[0].user_name }}/bin/"
    owner: "{{ item[0].user_name }}"
    group: "{{ item[0].user_name }}"
    mode: "{{ item[1].mode }}"
  with_nested:
    - "{{ restricted_accounts }}"
    - "{{ restricted_commands }}"
  when: ( "{{ item.user_name }}" is defined and "{{ item.user_state }}" == "present" )
  tags:
    - os_restricted_shell

- name: Update .bash_profile
  lineinfile:
    path: "/home/{{ item.user_name }}/.bash_profile" 
    regexp: '^PATH'
    line: 'PATH=$HOME/bin'
  with_items:
    - "{{ restricted_accounts }}"
  when: ( "{{ item.user_name }}" is defined and "{{ item.user_state }}" == "present" )
  tags:
    - os_restricted_shell
  
- name: Update .bash_profile attribute to immutable
  file:
    path: "/home/{{ item.user_name }}/.bash_profile" 
    attributes: "i"
  with_items:
    - "{{ restricted_accounts }}"
  when: ( "{{ item.user_name }}" is defined and "{{ item.user_state }}" == "present" )
  tags:
    - os_restricted_shell
