---
- name: Check if rbash exists.
  stat:
    path: /bin/rbash
  register: sym
  tags:
    - os_restricted_shell

- name: Make rbash
  copy:
    src: /bin/bash
    dest: /bin/rbash
    owner: root
    group: root
    mode: 0755
  when: sym.stat.exists == False
  tags:
    - os_restricted_shell

- name: Setup Restricted shell for user.
  user:
    name: "{{ item.user }}"
    shell: /bin/rbash
    password: "{{ item.pw | password_hash('sha512','mysalt') }}"
    state: present
  with_items:
    - "{{ restricted_accounts }}"
  tags:
    - os_restricted_shell

- name: Create home bin directory
  file:
    path: "/home/{{ item.user }}/bin"
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    state: directory
  with_items:
    - "{{ restricted_accounts }}"
  tags:
    - os_restricted_shell

- name: Copy commands to restricted shell bin folder
  copy:
    src: "{{ item[1].command }}"
    dest: "/home/{{ item[0].user }}/bin/"
    owner: "{{ item[0].user }}"
    group: "{{ item[0].user }}"
    mode: "{{ item[1].mode }}"
  with_nested:
    - "{{ restricted_accounts }}"
    - "{{ restricted_commands }}"
   

- name: Update .bash_profile
  lineinfile:
    path: "/home/{{ item.user }}/.bash_profile" 
    regexp: '^PATH'
    line: 'PATH=$HOME/bin'
  with_items:
    - "{{ restricted_accounts }}"
  tags:
    - os_restricted_shell

  
