---
#- name: Check for required variables
#  fail: 
#    msg: "Must provide xxx to -e"
#  when: ( something is not defined ) or  ( another thing is not defined )

- name: Shutdown ESXi hosts
  vmware_host_powerstate:
    hostname: '{{ deployment_vcenter }}'
    username: '{{ deployment_user }}'
    password: '{{ deployment_pass }}'
    validate_certs: no
    state: '{{ host_state }}'
    force: '{{ host_force }}'
    esxi_hostname: '{{ esxi_host }}'
  delegate_to: localhost
  tags:
    - shuts_esxi
