---
- name: Generate test report folder "{{ test_folder }}"
  file:
    path: "{{ test_folder }}"
    mode: 0755
    state: directory
  delegate_to: localhost
  tags: sf_pretest

- name: Generate test report "{{ test_filename }}"
  file:
    path: "{{ test_filename }}.txt"
    mode: 0755
    state: touch
  delegate_to: localhost
  tags: sf_pretest

########################################################################################################
#- name: Register "{{ check_chrootdir_path }}" to be checked 
#  stat: 
#    path: "{{ check_chrootdir_path }}"
#  register: p
#  delegate_to: localhost
#  tags: sf_pretest
#
########################################################################################################
#- name: Ensure "{{ check_chrootdir_path }}" permission is "{{ check_chrootdir_owner }}" 
#  set_fact:
#    check_chrootdir_owner_state: PASSED
#  when: p.stat.pw_name is defined
#  delegate_to: localhost
#  tags: sf_pretest
#
#- name:
#  lineinfile:
#    path: "{{ test_filename }}.txt"
#    line: "{{ check_chrootdir_path }} owner ownership is {{ check_chrootdir_owner }}: \t{{ check_chrootdir_owner_state }}"  
#  when: p is defined
#  delegate_to: localhost
#  tags: sf_pretest
#
#######################################################################################################
#
- name: Register "{{ test_dir }}" to be checked
  stat:
    path: "{{ item.path }}"
  with_items: "{{ test_dir }}"
  register: p
  delegate_to: localhost
  tags: sf_pretest

- name:
  debug:
    msg: "{{ item.stat.exists }}"
  with_items: "{{ p.results }}"

- name: Ensure path exists
  set_fact:
    default_state: PASSED
  when:  item.stat.exists
  with_items: "{{ p.results }}"
  #delegate_to: localhost
  tags: sf_pretest

- name:
  lineinfile:
    path: "{{ test_filename }}.txt"
    line: "{{ item.item.path }} exists: \t{{ item.stat.exists }}"  
    #when: item.stat.exists
  with_items: "{{ p.results }}"
  delegate_to: localhost
  tags: sf_pretest

#- name: Summary of this checks
#  debug:
#    msg:  "print ... {{ item.path }}"
#  with_items: "{{ test_dir }}"
#  delegate_to: localhost
#  tags: sf_pretest 
