---
FILE_SSHD_CONFIG                : /etc/ssh/sshd_config
SSHD_VALIDATE                   : sshd -t -f %s
SSHD_APPROVED_MACS              : MACs hmac-sha2-512,hmac-sha2-256
SSHD_APPROVED_MACS_REGEXP       : ^MACs
SSHD_APPROVED_CIPHERS           : Ciphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc
SSHD_APPROVED_CIPHERS_REGEXP    : ^Ciphers
SSHD_PERMIT_ROOT_LOGIN          : PermitRootLogin no
SSHD_PERMIT_ROOT_LOGIN_REGEXP   : ^PermitRootLogin
SSHD_PRINT_LASTLOG              : PrintLastLog yes
SSHD_PRINT_LASTLOG_REGEXP       : ^PrintLastLog
SSHD_BANNER_ISSUE               : Banner /etc/issue 
SSHD_BANNER_ISSUE_REGEXP        : ^Banner
