---
- name: Add user
  user:
    name: xxxman
    comment: xxx user
    #expires: -1 
    state: present

- name: Create .ssh directory
  file:
    path: /home/xxxman/.ssh
    state: directory
    owner: xxxman
    group: xxxman
    mode: 0700
    recurse: no

- name: Allow 'xxxman' sudo passwordless
  lineinfile:
    path: /etc/sudoers
    line: 'xxxman ALL=NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'


- name: Download xxxman pubkey
  get_url:
    url: "https://{{ satellite_server }}:9090/ssh/pubkey"
    dest: /home/xxxman/.ssh/authorized_keys
    validate_certs: no
    owner: xxxman
    group: xxxman
    mode: 0600
    checksum: md5:ac5adb401e7124eb3a12997b0ba9dec0 

- name: Reenforce user account expiry.
  command: /usr/bin/chage -M -1 xxxman 
