backups:
  - name: system1 
    backup:
    - { type: sys,         name: "daily3",        tmpl: "dsm.sys.j2",           svr: "Backup03" }
  - name: 127.0.0.1
    backup:
    - { type: sys,         name: "daily3",        tmpl: "dsm.sys.j2",           svr: "Backup03" }
    - { type: daily,       name: "daily3",        tmpl: "daily.opt.j2",         svr: "Backup03", addr: "backup03.test.lab",  port: 1503 }
    - { type: monthly,     name: "monthly4",      tmpl: "monthly.opt.j2",       svr: "Backup04", addr: "backup04.test.lab",  port: 1504 }
    - { type: daily_ora,   name: "ora_daily3",    tmpl: "daily_ora.opt.j2",     svr: "Backup07", addr: "backup07.test.lab",  port: 1507 }
    - { type: monthly_ora, name: "ora_monthly4",  tmpl: "monthly_ora.opt.j2",   svr: "Backup08", addr: "backup08.test.lab",  port: 1508 }
