---
#- name: Check for required variables
#  fail: 
#    msg: "Must provide xxx to -e"
#  when: ( something is not defined ) or  ( another thing is not defined )

- name: Transfer boot iso to vCenter 
  vsphere_copy:
    host: '{{ deployment_vcenter }}'
    login: '{{ deployment_user }}'
    password: '{{ deployment_pass }}'
    datacenter: '{{ deployment_datacenter }}'
    datastore: '{{ deployment_iso_datastore }}'
    #src: '/tmp/{{ inventory_hostname }}.iso'
    #path: '{{ deployment_iso_path }}/{{ inventory_hostname }}.iso'
    src: '{{ bootiso_local_dir }}/{{ bootiso_filename }}'
    path: '{{ deployment_iso_path }}/{{ bootiso_filename }}'
    validate_certs: no
  delegate_to: localhost
  tags:
    - vds_file_transfer

#- name: Transfer file to SkullDataStore if it is mounted.
#  copy:
#    src: "{{ iso_local_target_dir }}{{ iso_local_target_filename }}"
#    dest: /data/
#  with_items: "{{ ansible_mounts }}"
#  when: '"SkullDataStore" in item.device'
#  tags:
#    - build_iso 
