---
- name: Add docker-ce repository
  yum_repository:
    name: docker-ce
    description: Docker CE repo
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo

- name: Add K8s repository
  file:
    src: files/kubernates.repo
    dest: /etc/yum.repos.d/kubernates.repo
    state: file
    owner: root
    group: root
    mode: 0755

- name: Install k8s packages
  yum:
    name: "{{ packages}}"
    state: present
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - kubectl
    - kubeadm
    - kubelet

- name: Enable firewall ports
  firewalld:
    zone: public
    port: '{{ item }}'
    permanent: yes
    state: enabled
  with_items:
    - '6443/tcp'
    - '10250/tcp'

- name: Enable k8s services
  service:
    name: "{{ services }}"
    state: started
    enabled: yes
  vars:
    services:
    - docker
    - kubelet
