---
- name: Adding default variables
  include_vars: "../defaults/main.yml"

- name: Adding vm tasks
  import_tasks: vm/vm_create.yml
  when: ( platform_target == "vm" and action == "create" )

- name: Adding vm tasks
  import_tasks: vm/vm_destroy.yml
  when: ( platform_target == "vm" and action == "destroy" )

- name: Adding esxi tasks
  import_tasks: esxi/esxi.yml
  when: ( platform_target == "esxi" and action == "create" )
